In [6]:
result=0 
for i in range(50):
    result +=i

In [22]:
L = list(range(14))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

In [23]:
L2 = [str(c)for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13']

In [24]:
L3 = [True, "5",3.56,44, 8.92]
[type(item)for item in L3]

[bool, str, float, int, float]

In [25]:
import array
L= list(range(8))
A= array.array('i',L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7])

In [28]:
import numpy as np

In [30]:
np.array([2.64,9.45,55,81])

array([ 2.64,  9.45, 55.  , 81.  ])

In [33]:
np.array([range(i,i+6) for i in [2,4,8]])

array([[ 2,  3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8,  9],
       [ 8,  9, 10, 11, 12, 13]])

In [36]:
np.full((4,3),8)

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [40]:
np.ones((2,3),dtype=str)

array([['1', '1', '1'],
       ['1', '1', '1']], dtype='<U1')

In [44]:
np.zeros((2,2),dtype='int32')

array([[0, 0],
       [0, 0]])

In [45]:
np.arange(5,40,5)

array([ 5, 10, 15, 20, 25, 30, 35])

In [49]:
np.arange(8,12,5)

array([8])

In [52]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [54]:
np.random.random((4,2))

array([[0.44014963, 0.83758627],
       [0.06058057, 0.55902049],
       [0.73980915, 0.82862183],
       [0.51845629, 0.44923636]])

In [55]:
np.random.randint(5,20,(2,3))

array([[18,  7,  8],
       [12, 13, 16]])

In [56]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [57]:
np.empty(4)

array([0.90654996, 0.49682491, 0.30752543, 0.21778795])

In [61]:
np.random.randint(15,size=(3,3))

array([[3, 9, 0],
       [3, 4, 4],
       [9, 2, 3]])